version: "2.1"
services:
  flooding:
    image: emergent-overlays-worker
    volumes:
      - './experiments:/usr/emrg-ovrl/experiments'
      - './src:/usr/emrg-ovrl/src'
      - 'results:/usr/emrg-ovrl/results'
    environment:
      - EXPE_CONF_FILE=/usr/emrg-ovrl/experiments/configs/unit-tests/n_11_d_0_tr_75_a_500x500_idx_0_p_flooding.ini
    healthcheck:
        test: exit 0
  mpr:
    image: emergent-overlays-worker
    volumes:
      - './experiments:/usr/emrg-ovrl/experiments'
      - './src:/usr/emrg-ovrl/src'
      - 'results:/usr/emrg-ovrl/results'
    environment:
      - EXPE_CONF_FILE=/usr/emrg-ovrl/experiments/configs/unit-tests/n_11_d_0_tr_75_a_500x500_idx_0_p_mpr.ini
    healthcheck:
        test: exit 0
  hybrid:
    image: emergent-overlays-worker
    volumes:
      - './experiments:/usr/emrg-ovrl/experiments'
      - './src:/usr/emrg-ovrl/src'
      - 'results:/usr/emrg-ovrl/results'
    environment:
      - EXPE_CONF_FILE=/usr/emrg-ovrl/experiments/configs/unit-tests/n_11_d_0_tr_75_a_500x500_idx_0_p_hybrid.ini
    healthcheck:
        test: exit 0
  plotter:
    image: emergent-overlays-plotter
    volumes:
      - './src:/usr/emrg-ovrl/src'
      - 'results:/usr/emrg-ovrl/results'
    depends_on:
      flooding:
        condition: service_healthy
      mpr:
        condition: service_healthy
      hybrid:
        condition: service_healthy
