version: "2.1"
services:
  trace_generator:
    env_file: .env
    build:
      context: ./dockerfiles/trace_generator
    image: trace_generator:latest
    volumes:
      - './src/scripts/topologies:/usr/emrg-ovrl/src/scripts/topologies'
      - './experiments/configs/in_common:/usr/emrg-ovrl/experiments/configs/in_common'
      - './experiments/configs/built_configs:/usr/emrg-ovrl/experiments/configs/built_configs'
      - './experiments/networks/built_topologies:/usr/emrg-ovrl/experiments/networks/built_topologies'
  worker:
    build:
      context: .
      dockerfile: ./dockerfiles/worker/Dockerfile
    image: worker:latest
    volumes:
      - './experiments/configs/in_common:/usr/emrg-ovrl/experiments/configs/in_common'
      - './experiments/configs/built_configs:/usr/emrg-ovrl/experiments/configs/built_configs'
      - './experiments/networks/built_topologies:/usr/emrg-ovrl/experiments/networks/built_topologies'
      - './results:/usr/emrg-ovrl/results'
  plotter:
    build:
      context: .
      dockerfile: ./dockerfiles/plotter/Dockerfile
    image: plotter:latest
    volumes:
      - './experiments/configs/built_configs:/usr/emrg-ovrl/experiments/configs/built_configs'
      - './results:/usr/emrg-ovrl/results'
