//
// Generated file, do not edit! Created by nedtool 4.6 from ewma2/ewmaMsgs.msg.
//

#ifndef _INET__EWMA_EWMAMSGS_M_H_
#define _INET__EWMA_EWMAMSGS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "broadcasting/BroadcastingAppBase_m.h"
using inet::broadcasting::Broadcast;
// }}


namespace inet {
namespace ewma {

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:25</tt> by nedtool.
 * <pre>
 * packet EWMABroadcast extends inet::broadcasting::Broadcast
 * {
 *     string covered[];
 * }
 * </pre>
 */
class EWMABroadcast : public ::inet::broadcasting::Broadcast
{
  protected:
    opp_string *covered_var; // array ptr
    unsigned int covered_arraysize;

  private:
    void copy(const EWMABroadcast& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EWMABroadcast&);

  public:
    EWMABroadcast(const char *name=NULL, int kind=0);
    EWMABroadcast(const EWMABroadcast& other);
    virtual ~EWMABroadcast();
    EWMABroadcast& operator=(const EWMABroadcast& other);
    virtual EWMABroadcast *dup() const {return new EWMABroadcast(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setCoveredArraySize(unsigned int size);
    virtual unsigned int getCoveredArraySize() const;
    virtual const char * getCovered(unsigned int k) const;
    virtual void setCovered(unsigned int k, const char * covered);
};

inline void doPacking(cCommBuffer *b, EWMABroadcast& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, EWMABroadcast& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:29</tt> by nedtool.
 * <pre>
 * packet ConnectMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class ConnectMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const ConnectMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectMWST&);

  public:
    ConnectMWST(const char *name=NULL, int kind=0);
    ConnectMWST(const ConnectMWST& other);
    virtual ~ConnectMWST();
    ConnectMWST& operator=(const ConnectMWST& other);
    virtual ConnectMWST *dup() const {return new ConnectMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ConnectMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConnectMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:33</tt> by nedtool.
 * <pre>
 * packet InitiateMWST
 * {
 *     string fragmentId;
 *     string sender;
 * }
 * </pre>
 */
class InitiateMWST : public ::cPacket
{
  protected:
    opp_string fragmentId_var;
    opp_string sender_var;

  private:
    void copy(const InitiateMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InitiateMWST&);

  public:
    InitiateMWST(const char *name=NULL, int kind=0);
    InitiateMWST(const InitiateMWST& other);
    virtual ~InitiateMWST();
    InitiateMWST& operator=(const InitiateMWST& other);
    virtual InitiateMWST *dup() const {return new InitiateMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFragmentId() const;
    virtual void setFragmentId(const char * fragmentId);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, InitiateMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InitiateMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:38</tt> by nedtool.
 * <pre>
 * packet TestMWST
 * {
 *     string fragmentId;
 *     string sender;
 * }
 * </pre>
 */
class TestMWST : public ::cPacket
{
  protected:
    opp_string fragmentId_var;
    opp_string sender_var;

  private:
    void copy(const TestMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TestMWST&);

  public:
    TestMWST(const char *name=NULL, int kind=0);
    TestMWST(const TestMWST& other);
    virtual ~TestMWST();
    TestMWST& operator=(const TestMWST& other);
    virtual TestMWST *dup() const {return new TestMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFragmentId() const;
    virtual void setFragmentId(const char * fragmentId);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, TestMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TestMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:43</tt> by nedtool.
 * <pre>
 * packet AcceptMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class AcceptMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const AcceptMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AcceptMWST&);

  public:
    AcceptMWST(const char *name=NULL, int kind=0);
    AcceptMWST(const AcceptMWST& other);
    virtual ~AcceptMWST();
    AcceptMWST& operator=(const AcceptMWST& other);
    virtual AcceptMWST *dup() const {return new AcceptMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, AcceptMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AcceptMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:47</tt> by nedtool.
 * <pre>
 * packet RejectMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class RejectMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const RejectMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RejectMWST&);

  public:
    RejectMWST(const char *name=NULL, int kind=0);
    RejectMWST(const RejectMWST& other);
    virtual ~RejectMWST();
    RejectMWST& operator=(const RejectMWST& other);
    virtual RejectMWST *dup() const {return new RejectMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, RejectMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RejectMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:51</tt> by nedtool.
 * <pre>
 * packet ReportMWST
 * {
 *     double weight;
 *     string sender;
 * }
 * </pre>
 */
class ReportMWST : public ::cPacket
{
  protected:
    double weight_var;
    opp_string sender_var;

  private:
    void copy(const ReportMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReportMWST&);

  public:
    ReportMWST(const char *name=NULL, int kind=0);
    ReportMWST(const ReportMWST& other);
    virtual ~ReportMWST();
    ReportMWST& operator=(const ReportMWST& other);
    virtual ReportMWST *dup() const {return new ReportMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getWeight() const;
    virtual void setWeight(double weight);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ReportMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ReportMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:56</tt> by nedtool.
 * <pre>
 * packet ChangeRootMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class ChangeRootMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const ChangeRootMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ChangeRootMWST&);

  public:
    ChangeRootMWST(const char *name=NULL, int kind=0);
    ChangeRootMWST(const ChangeRootMWST& other);
    virtual ~ChangeRootMWST();
    ChangeRootMWST& operator=(const ChangeRootMWST& other);
    virtual ChangeRootMWST *dup() const {return new ChangeRootMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ChangeRootMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ChangeRootMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>ewma2/ewmaMsgs.msg:60</tt> by nedtool.
 * <pre>
 * packet InNewFragment
 * {
 *     string sender;
 *     string fragmentId;
 * }
 * </pre>
 */
class InNewFragment : public ::cPacket
{
  protected:
    opp_string sender_var;
    opp_string fragmentId_var;

  private:
    void copy(const InNewFragment& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InNewFragment&);

  public:
    InNewFragment(const char *name=NULL, int kind=0);
    InNewFragment(const InNewFragment& other);
    virtual ~InNewFragment();
    InNewFragment& operator=(const InNewFragment& other);
    virtual InNewFragment *dup() const {return new InNewFragment(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual const char * getFragmentId() const;
    virtual void setFragmentId(const char * fragmentId);
};

inline void doPacking(cCommBuffer *b, InNewFragment& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InNewFragment& obj) {obj.parsimUnpack(b);}

} // namespace ewma
} // namespace inet

#endif // ifndef _INET__EWMA_EWMAMSGS_M_H_

