//
// Generated file, do not edit! Created by nedtool 4.6 from cds/cdsMsgs.msg.
//

#ifndef _INET__CDS2_CDSMSGS_M_H_
#define _INET__CDS2_CDSMSGS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "broadcasting/BroadcastingAppBase.h"
    typedef inet::BroadcastingAppBase::Neighbor *NePo; 
// }}


namespace inet {
namespace cds2 {

/**
 * Class generated from <tt>cds/cdsMsgs.msg:21</tt> by nedtool.
 * <pre>
 * packet Neighbors
 * {
 *     string neighbors[];
 *     int hopLevels[];
 *     double xs[];
 *     double ys[];
 *     int maxHopLevel;
 *     string sender;
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class Neighbors : public ::cPacket
{
  protected:
    opp_string *neighbors_var; // array ptr
    unsigned int neighbors_arraysize;
    int *hopLevels_var; // array ptr
    unsigned int hopLevels_arraysize;
    double *xs_var; // array ptr
    unsigned int xs_arraysize;
    double *ys_var; // array ptr
    unsigned int ys_arraysize;
    int maxHopLevel_var;
    opp_string sender_var;
    double x_var;
    double y_var;

  private:
    void copy(const Neighbors& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Neighbors&);

  public:
    Neighbors(const char *name=NULL, int kind=0);
    Neighbors(const Neighbors& other);
    virtual ~Neighbors();
    Neighbors& operator=(const Neighbors& other);
    virtual Neighbors *dup() const {return new Neighbors(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setNeighborsArraySize(unsigned int size);
    virtual unsigned int getNeighborsArraySize() const;
    virtual const char * getNeighbors(unsigned int k) const;
    virtual void setNeighbors(unsigned int k, const char * neighbors);
    virtual void setHopLevelsArraySize(unsigned int size);
    virtual unsigned int getHopLevelsArraySize() const;
    virtual int getHopLevels(unsigned int k) const;
    virtual void setHopLevels(unsigned int k, int hopLevels);
    virtual void setXsArraySize(unsigned int size);
    virtual unsigned int getXsArraySize() const;
    virtual double getXs(unsigned int k) const;
    virtual void setXs(unsigned int k, double xs);
    virtual void setYsArraySize(unsigned int size);
    virtual unsigned int getYsArraySize() const;
    virtual double getYs(unsigned int k) const;
    virtual void setYs(unsigned int k, double ys);
    virtual int getMaxHopLevel() const;
    virtual void setMaxHopLevel(int maxHopLevel);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
};

inline void doPacking(cCommBuffer *b, Neighbors& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Neighbors& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>cds/cdsMsgs.msg:34</tt> by nedtool.
 * <pre>
 * // Used to request the hops of a node
 * // the max_hop_value must be >= 0
 * packet RequestNeighbors
 * {
 *     string sender;
 *     int maxHopLevel;
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class RequestNeighbors : public ::cPacket
{
  protected:
    opp_string sender_var;
    int maxHopLevel_var;
    double x_var;
    double y_var;

  private:
    void copy(const RequestNeighbors& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RequestNeighbors&);

  public:
    RequestNeighbors(const char *name=NULL, int kind=0);
    RequestNeighbors(const RequestNeighbors& other);
    virtual ~RequestNeighbors();
    RequestNeighbors& operator=(const RequestNeighbors& other);
    virtual RequestNeighbors *dup() const {return new RequestNeighbors(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual int getMaxHopLevel() const;
    virtual void setMaxHopLevel(int maxHopLevel);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
};

inline void doPacking(cCommBuffer *b, RequestNeighbors& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RequestNeighbors& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>cds/cdsMsgs.msg:41</tt> by nedtool.
 * <pre>
 * packet MarkerChanged
 * {
 *     string sender;
 *     bool marker;
 * }
 * </pre>
 */
class MarkerChanged : public ::cPacket
{
  protected:
    opp_string sender_var;
    bool marker_var;

  private:
    void copy(const MarkerChanged& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MarkerChanged&);

  public:
    MarkerChanged(const char *name=NULL, int kind=0);
    MarkerChanged(const MarkerChanged& other);
    virtual ~MarkerChanged();
    MarkerChanged& operator=(const MarkerChanged& other);
    virtual MarkerChanged *dup() const {return new MarkerChanged(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual bool getMarker() const;
    virtual void setMarker(bool marker);
};

inline void doPacking(cCommBuffer *b, MarkerChanged& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MarkerChanged& obj) {obj.parsimUnpack(b);}

} // namespace cds2
} // namespace inet

#endif // ifndef _INET__CDS2_CDSMSGS_M_H_

