//
// Generated file, do not edit! Created by nedtool 4.6 from mpr2/mprMsgs.msg.
//

#ifndef _INET__MPR2_MPRMSGS_M_H_
#define _INET__MPR2_MPRMSGS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {
namespace mpr2 {

/**
 * Class generated from <tt>mpr2/mprMsgs.msg:20</tt> by nedtool.
 * <pre>
 * packet Neighbours
 * {
 *     string neighbours;
 *     string emitter;
 * }
 * </pre>
 */
class Neighbours : public ::cPacket
{
  protected:
    opp_string neighbours_var;
    opp_string emitter_var;

  private:
    void copy(const Neighbours& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Neighbours&);

  public:
    Neighbours(const char *name=NULL, int kind=0);
    Neighbours(const Neighbours& other);
    virtual ~Neighbours();
    Neighbours& operator=(const Neighbours& other);
    virtual Neighbours *dup() const {return new Neighbours(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getNeighbours() const;
    virtual void setNeighbours(const char * neighbours);
    virtual const char * getEmitter() const;
    virtual void setEmitter(const char * emitter);
};

inline void doPacking(cCommBuffer *b, Neighbours& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Neighbours& obj) {obj.parsimUnpack(b);}

} // namespace mpr2
} // namespace inet

#endif // ifndef _INET__MPR2_MPRMSGS_M_H_

