[General]
record-eventlog = true

# status
**.hasStatus = true
**.networkLayer.ip.forceBroadcast = true

**.energyStorage.nominalCapacity = 0.20J
**.energyStorage.nodeShutdownCapacity = 0J
**.energyStorage.initialCapacity = this.nominalCapacity

# Radio settings
**.wlan[*].radio.transmitter.maxCommunicationRange = 75m
**.wlan[*].radio.receiver.ignoreInterference = true

**.numUdpApps = 1

[Config cds]
network = Backbone

*.host{1..3}.udpApp[0].typename = "PureFlooding" 
*.host{4..7}.udpApp[0].typename = "InteroperableBroadcast"

**.udpApp[0].messageLength = 200B

**.udpApp[0].startTime = 0s
**.udpApp[0].stopTime = 10.1s

**.udpApp[0].sendInterval = uniform(0.09s, 0.1s)
*.host2.udpApp[0].isSource = true
**.udpApp[0].withCtrlMsg = true
**.udpApp[0].ctrlMsgInterval = uniform(0.39s, .4s)

[Config flooding]
network = Backbone

**.udpApp[0].typename = "PureFlooding"

**.udpApp[0].messageLength = 200B

**.udpApp[0].startTime = 0s
**.udpApp[0].stopTime = 10.1s

**.udpApp[0].sendInterval = uniform(0.09s, 0.1s)
*.host2.udpApp[0].isSource = true

[Config ping]
network = UnitTest

**.udpApp[0].typename = "InteroperableBroadcast" 

**.udpApp[0].messageLength = 200B
**.udpApp[0].startTime = 0s
#**.udpApp[0].withCtrlMsg = true
**.udpApp[0].stopTime = 1.6s
**.udpApp[0].sendInterval = 0.5s
*.host1.udpApp[0].isSource = true
