//
// Generated file, do not edit! Created by nedtool 4.6 from mwst2/MWSTMsgs.msg.
//

#ifndef _INET_MWSTMSGS_M_H_
#define _INET_MWSTMSGS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:18</tt> by nedtool.
 * <pre>
 * packet HelloMWST
 * {
 *     string sender;
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class HelloMWST : public ::cPacket
{
  protected:
    opp_string sender_var;
    double x_var;
    double y_var;

  private:
    void copy(const HelloMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HelloMWST&);

  public:
    HelloMWST(const char *name=NULL, int kind=0);
    HelloMWST(const HelloMWST& other);
    virtual ~HelloMWST();
    HelloMWST& operator=(const HelloMWST& other);
    virtual HelloMWST *dup() const {return new HelloMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
};

inline void doPacking(cCommBuffer *b, HelloMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, HelloMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:24</tt> by nedtool.
 * <pre>
 * packet ConnectMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class ConnectMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const ConnectMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectMWST&);

  public:
    ConnectMWST(const char *name=NULL, int kind=0);
    ConnectMWST(const ConnectMWST& other);
    virtual ~ConnectMWST();
    ConnectMWST& operator=(const ConnectMWST& other);
    virtual ConnectMWST *dup() const {return new ConnectMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ConnectMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ConnectMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:28</tt> by nedtool.
 * <pre>
 * packet InitiateMWST
 * {
 *     string fragmentId;
 *     string sender;
 * }
 * </pre>
 */
class InitiateMWST : public ::cPacket
{
  protected:
    opp_string fragmentId_var;
    opp_string sender_var;

  private:
    void copy(const InitiateMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InitiateMWST&);

  public:
    InitiateMWST(const char *name=NULL, int kind=0);
    InitiateMWST(const InitiateMWST& other);
    virtual ~InitiateMWST();
    InitiateMWST& operator=(const InitiateMWST& other);
    virtual InitiateMWST *dup() const {return new InitiateMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFragmentId() const;
    virtual void setFragmentId(const char * fragmentId);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, InitiateMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InitiateMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:34</tt> by nedtool.
 * <pre>
 * packet TestMWST
 * {
 *     string fragmentId;
 *     string sender;
 * }
 * </pre>
 */
class TestMWST : public ::cPacket
{
  protected:
    opp_string fragmentId_var;
    opp_string sender_var;

  private:
    void copy(const TestMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TestMWST&);

  public:
    TestMWST(const char *name=NULL, int kind=0);
    TestMWST(const TestMWST& other);
    virtual ~TestMWST();
    TestMWST& operator=(const TestMWST& other);
    virtual TestMWST *dup() const {return new TestMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFragmentId() const;
    virtual void setFragmentId(const char * fragmentId);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, TestMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TestMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:39</tt> by nedtool.
 * <pre>
 * packet AcceptMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class AcceptMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const AcceptMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AcceptMWST&);

  public:
    AcceptMWST(const char *name=NULL, int kind=0);
    AcceptMWST(const AcceptMWST& other);
    virtual ~AcceptMWST();
    AcceptMWST& operator=(const AcceptMWST& other);
    virtual AcceptMWST *dup() const {return new AcceptMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, AcceptMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AcceptMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:43</tt> by nedtool.
 * <pre>
 * packet RejectMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class RejectMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const RejectMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RejectMWST&);

  public:
    RejectMWST(const char *name=NULL, int kind=0);
    RejectMWST(const RejectMWST& other);
    virtual ~RejectMWST();
    RejectMWST& operator=(const RejectMWST& other);
    virtual RejectMWST *dup() const {return new RejectMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, RejectMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RejectMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:47</tt> by nedtool.
 * <pre>
 * packet ReportMWST
 * {
 *     double weight;
 *     string sender;
 * }
 * </pre>
 */
class ReportMWST : public ::cPacket
{
  protected:
    double weight_var;
    opp_string sender_var;

  private:
    void copy(const ReportMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReportMWST&);

  public:
    ReportMWST(const char *name=NULL, int kind=0);
    ReportMWST(const ReportMWST& other);
    virtual ~ReportMWST();
    ReportMWST& operator=(const ReportMWST& other);
    virtual ReportMWST *dup() const {return new ReportMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getWeight() const;
    virtual void setWeight(double weight);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ReportMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ReportMWST& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>mwst2/MWSTMsgs.msg:52</tt> by nedtool.
 * <pre>
 * packet ChangeRootMWST
 * {
 *     string sender;
 * }
 * </pre>
 */
class ChangeRootMWST : public ::cPacket
{
  protected:
    opp_string sender_var;

  private:
    void copy(const ChangeRootMWST& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ChangeRootMWST&);

  public:
    ChangeRootMWST(const char *name=NULL, int kind=0);
    ChangeRootMWST(const ChangeRootMWST& other);
    virtual ~ChangeRootMWST();
    ChangeRootMWST& operator=(const ChangeRootMWST& other);
    virtual ChangeRootMWST *dup() const {return new ChangeRootMWST(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
};

inline void doPacking(cCommBuffer *b, ChangeRootMWST& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ChangeRootMWST& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef _INET_MWSTMSGS_M_H_

